name: runner-actions

on: push

jobs:
  runner-ubuntu:
    name: runner-actions
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Print folder
        run: |
          cd /home/runner/work/git-hub-actions/git-hub-actions/.github/
          ls -la
      
