name: 05 - 01 - event filter

on:
  pull_request:
    type:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event name
        run: | 
          echo "Event name: ${{ github.event_name }} event ."